// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfJ7V3CfVYHSUVCp_Th60AaJvOH_VoYvE',
    appId: '1:158492273296:web:d88562425230ccd84bc615',
    messagingSenderId: '158492273296',
    projectId: 'fashion-fusion-c717a',
    authDomain: 'fashion-fusion-c717a.firebaseapp.com',
    storageBucket: 'fashion-fusion-c717a.firebasestorage.app',
    measurementId: 'G-T9GSSKERCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2N2DiYc7Rr8MqdXGQrEtwobY5n_2Kh6g',
    appId: '1:158492273296:android:24b87005830afaac4bc615',
    messagingSenderId: '158492273296',
    projectId: 'fashion-fusion-c717a',
    storageBucket: 'fashion-fusion-c717a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4-5LWv3okfc1ldidQFUJeDIa4FMfGufc',
    appId: '1:158492273296:ios:b66d4bbb8f574b3e4bc615',
    messagingSenderId: '158492273296',
    projectId: 'fashion-fusion-c717a',
    storageBucket: 'fashion-fusion-c717a.firebasestorage.app',
    iosBundleId: 'com.example.fashionFusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4-5LWv3okfc1ldidQFUJeDIa4FMfGufc',
    appId: '1:158492273296:ios:b66d4bbb8f574b3e4bc615',
    messagingSenderId: '158492273296',
    projectId: 'fashion-fusion-c717a',
    storageBucket: 'fashion-fusion-c717a.firebasestorage.app',
    iosBundleId: 'com.example.fashionFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfJ7V3CfVYHSUVCp_Th60AaJvOH_VoYvE',
    appId: '1:158492273296:web:1ad5f44235e4392d4bc615',
    messagingSenderId: '158492273296',
    projectId: 'fashion-fusion-c717a',
    authDomain: 'fashion-fusion-c717a.firebaseapp.com',
    storageBucket: 'fashion-fusion-c717a.firebasestorage.app',
    measurementId: 'G-77K7T7Z8YR',
  );
}
