// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi5LGV3hwqVJCwihmEx924_jy7sEGkDAA',
    appId: '1:595060564964:web:d370a37077292d0c935df1',
    messagingSenderId: '595060564964',
    projectId: 'fashionfusion-aa06d',
    authDomain: 'fashionfusion-aa06d.firebaseapp.com',
    storageBucket: 'fashionfusion-aa06d.firebasestorage.app',
    measurementId: 'G-66P1MTE8X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9VkbFuBZWpL0iEvcXY_hUUF0DIHqZ0vM',
    appId: '1:595060564964:android:7c42b6cf654d7f55935df1',
    messagingSenderId: '595060564964',
    projectId: 'fashionfusion-aa06d',
    storageBucket: 'fashionfusion-aa06d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSC0Q3hLA_aTfsB3GRAG5pmXKE9Xu73Gs',
    appId: '1:595060564964:ios:5ddcd0870091c384935df1',
    messagingSenderId: '595060564964',
    projectId: 'fashionfusion-aa06d',
    storageBucket: 'fashionfusion-aa06d.firebasestorage.app',
    iosBundleId: 'com.example.fashionFusion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSC0Q3hLA_aTfsB3GRAG5pmXKE9Xu73Gs',
    appId: '1:595060564964:ios:5ddcd0870091c384935df1',
    messagingSenderId: '595060564964',
    projectId: 'fashionfusion-aa06d',
    storageBucket: 'fashionfusion-aa06d.firebasestorage.app',
    iosBundleId: 'com.example.fashionFusion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi5LGV3hwqVJCwihmEx924_jy7sEGkDAA',
    appId: '1:595060564964:web:2c1b1dcf649edad6935df1',
    messagingSenderId: '595060564964',
    projectId: 'fashionfusion-aa06d',
    authDomain: 'fashionfusion-aa06d.firebaseapp.com',
    storageBucket: 'fashionfusion-aa06d.firebasestorage.app',
    measurementId: 'G-BKPXWKEQ2Q',
  );

}